---
- name: configure L-111_2_3_4-1
  hosts:
    - l-111_2_3_4-1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: set identity
      community.routeros.command:
        commands:
          - /system identity set name=MT-CHR-5
    - name: adjust console settings
      community.routeros.command:
        commands:
          - /system console screen set blank-interval=never line-count=40

    - name: assign addresses
      community.routeros.command:
        commands:
          - /ip address add address=10.11.11.11/24 interface=ether1 network=10.11.11.0
          - /ip address add address=10.11.12.11/24 interface=ether2 network=10.11.12.0
          - /ip address add address=10.11.13.11/24 interface=ether3 network=10.11.13.0
          - /ip address add address=10.11.14.11/24 interface=ether4 network=10.11.14.0
