---
- name: configure L-113-2
  hosts:
    - L-113-2
  connection: network_cli
  gather_facts: false
  tasks:
    - name: set identity
      community.routeros.command:
        commands:
          - /system identity set name=MT-CHR-113-2
    - name: adjust console settings
      community.routeros.command:
        commands:
          - /system console screen set blank-interval=never line-count=40

    - name: assign addresses
      community.routeros.command:
        commands:
          - /ip address add address=10.11.13.12/24 interface=ether1 network=10.11.13.0

    - name: integrate OSPF
      block:
        - name: add loopback bridge
          community.routeros.command:
            commands:
              - /interface bridge add name=Lo0

        - name: add loopback address
          community.routeros.command:
            commands:
              - /ip address add address=10.0.0.8 interface=Lo0 network=10.0.0.8

        - name: add OSPF instance
          community.routeros.command:
            commands:
              - /routing ospf instance add disabled=no name=ospfv2-inst router-id=10.0.0.8

        - name: add OSPF area
          community.routeros.command:
            commands:
              - /routing ospf area add disabled=no instance=ospfv2-inst name=ospfv2-a0

        - name: add OSPF interface-template for L-113
          community.routeros.command:
            commands:
              - /routing ospf interface-template add area=ospfv2-a0 disabled=no interfaces=Lo0,ether1 networks=10.11.13.0/24,10.0.0.8/32 use-bfd=yes

        - name: add BFD
          community.routeros.command:
            commands:
              - /routing bfd configuration add interfaces=ether1 min-rx=1s min-tx=1s
