---
- name: configure L-112-2
  hosts:
    - l-112-2
  connection: network_cli
  gather_facts: false
  tasks:
    - name: set identity
      community.routeros.command:
        commands:
          - /system identity set name=MT-CHR-6
    - name: adjust console settings
      community.routeros.command:
        commands:
          - /system console screen set blank-interval=never line-count=40
