---
- name: configure L-113-2
  hosts:
    - l-113-2
  connection: network_cli
  gather_facts: false
  tasks:
    - name: set identity
      community.routeros.command:
        commands:
          - /system identity set name=MT-CHR-8
