---
- name: configure L-112-2_122-1
  hosts:
    - L-112-2_122-1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: set identity
      community.routeros.command:
        commands:
          - /system identity set name=MT-CHR-112-2_122-1
    - name: adjust console settings
      community.routeros.command:
        commands:
          - /system console screen set blank-interval=never line-count=40

    - name: assign addresses
      community.routeros.command:
        commands:
          - /ip address add address=10.11.12.12/24 interface=ether1 network=10.11.12.0
          - /ip address add address=10.11.22.11/24 interface=ether2 network=10.11.22.11

    - name: integrate OSPF
      block:
        - name: add loopback bridge
          community.routeros.command:
            commands:
              - /interface bridge add name=Lo0

        - name: add loopback address
          community.routeros.command:
            commands:
              - /ip address add address=10.0.0.6 interface=Lo0 network=10.0.0.6

        - name: add OSPF instance
          community.routeros.command:
            commands:
              - /routing ospf instance add disabled=no name=ospfv2-inst router-id=10.0.0.6

        - name: add OSPF area
          community.routeros.command:
            commands:
              - /routing ospf area add disabled=no instance=ospfv2-inst name=ospfv2-a0

        - name: add OSPF interface-template for L-112
          community.routeros.command:
            commands:
              - /routing ospf interface-template add area=ospfv2-a0 disabled=no interfaces=Lo0,ether1 networks=10.11.12.0/24,10.0.0.6/32 use-bfd=yes

        - name: add BFD
          community.routeros.command:
            commands:
              - /routing bfd configuration add interfaces=ether1 min-rx=1s min-tx=1s
